### ISSUE TITLE
App Host Process Stopped

### ISSUE THREAD

**Issue by ChrisMurphy** [distancify/Seq.App.Freshdesk#2]
Hi, I have installed the app in seq through nuget which was successful. I then added an instance using my subdomain and api key.

When the app is invoked it appears that it is erroring as I'm not getting anything in FreshWorks and the app itself is logging diagnostic events as follows:

App host failed unexpectedly
`System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The system cannot find the file specified.
File name: 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at Seq.App.Freshdesk.FreshdeskClient..ctor(String subdomain, String identifier, String password)
   at Seq.App.Freshdesk.FreshdeskReactor.OnAttached()
   at Seq.Apps.GenericHost.AppHost..ctor(ILogger logger, String packageBinaryPath, String seqAppTypeName, App app, Host host)
   at Seq.Apps.GenericHost.Program.<Main>d__0.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

The status in the app card in Seq now states; "The app host process is stopped"

**Comment by levifuksz** [comment]
Hello

Apparently Seq apps need to have all their external dependencies bundled into the app's NuGet package in order for the app to load.

We are working on a fix for this issue.

**Comment by levifuksz** [comment]
The issue has been fixed in v1.1.1. Please update to it.

**Comment by ChrisMurphy** [comment]
Thanks, works fine now!
